baseurl = "http://hugo.dindi.net"
languagecode = "en-us"
metadataformat = "yaml"
pluralizelisttitles = false
title = "Hugo Themes"
[blackfriday]
plainIdAnchors = true
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
