baseurl = "http://hugo.dindi.net"
languagecode = "en-us"
metadataformat = "yaml"
defaultExtension: "md"
pluralizelisttitles = false
title = "Hugo Forestry"
[blackfriday]
plainIdAnchors = true
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
