baseurl = "http://hugo.dindi.net"
defaultextension = "md"
languagecode = "en-us"
metadataformat = "yaml"
pluralizelisttitles = false
title = "Hugo Forestry"
watch = true
[blackfriday]
plainIdAnchors = true
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
