
[author]
    name = "Steve Francia"
    github = "spf13"
	link = "http://gohugo.io/"
	
[params]
  # Date format, used by several themes
  DateForm = "Mon, Jan 2, 2006"
  DateFormat = "Mon, Jan 2, 2006"
  # Below fetched from theme Casper
  description = "Make the Web Fun Again"
  cover = "../../img/desk.jpg"
  author = "Hugo"
  authorlocation = "New York, USA"
  authorwebsite = "http://gohugo.io"
  bio= "Hugo is written for speed and performance. Great care has been taken to ensure that Hugo build time is as short as possible. We’re talking milliseconds to build your entire site for most setups."
  logo = "../../img/hugoSM.png"
  githubName = "spf13"
  twitterName = "spf13"
  hideHUGOSupport = false
  # poopshow
  blogHeader = "Hugo"
  tagline =  "Make the Web Fun Again"
  # {{ $.Site.BaseURL }}/img/{{ . }}
  headerimg = "../../../../img/desk.jpg"
  # Simple Hugo
  github = "bep"
  twitter = "bepsays"
  email = "your@mail.com"
  shortDescription = "Make the Web Fun Again"
  # Aglaus
  GravatarHash = "67d3f9eddc34d7649a92597c3978201f"
  ShowRelatedPost = true
  SyntaxHighlightTheme = "solarized_dark.min.css"
  # Greyshade
  twitter_user = "bepsays"
  github_user = "bep"
  facebook_like = true
  twitter_tweet_button = true
  google_plus_one = "true"
  # Hugo base
  mainIcon = "../../img/hugo.png"
  # Next
  perPage = 2
  # Hyde
  themeColor = "theme-base-08"
  # Robust
  ShowTagCloud = true
 
